#!/bin/bash

echo
[ "$(id -u)" -ne 0 ] && echo "Run with root permissions: 'sudo !!'" && echo && exit

echo 'Hostname:'
read -p '?: ' -e newHostname; echo
[ ! $newHostname ] && echo 'HostName Required!' && exit
oldHostname=$(cat /etc/hostname)
hostnamectl set-hostname $newHostname
sed -i "s/${oldHostname}/${newHostname}/g" /etc/hosts

echo 'Admin ID:'
read -p '?: ' -e adminID; echo
[ ! $adminID ] && echo 'Admin ID Required!' && exit

net ads join -v -U $adminID

systemctl enable winbind