#!/bin/bash

echo
[ "$(id -u)" -ne 0 ] && echo "Run with root permissions: 'sudo !!'" && echo && exit

echo 'Hostname:'
read -p '?: ' -e newHostName; echo
[ ! $newHostName ] && echo 'HostName Required!' && exit

oldHostName=$(cat /etc/hostname)
chattr -i /etc/hostname
chattr -i /etc/hosts

hostnamectl set-hostname $newHostName
sed -i "s/${oldHostName}/${newHostName}/g" /etc/hosts
chattr +i /etc/hostname
chattr +i /etc/hosts

echo 'Admin ID:'
read -p '?: ' -e adminID; echo
[ ! $adminID ] && echo 'Admin ID Required!' && exit

net ads join -U $adminID

systemctl enable --now smb
systemctl enable --now nmb
systemctl enable --now winbind