[libdefaults]
        default_realm = IFG.BR
        dns_lookup_realm = false
        dns_lookup_kdc = true
        # default_ccache_name = /run/user/%{uid}/krb5cc

[realms]
        IFG.BR = {
                admin_server = 10.11.0.16
                kdc = 10.11.0.16
                default_domain = IFG.BR
        }
        IFG = {
                admin_server = 10.11.0.16
                kdc = 10.11.0.16
                default_domain = IFG.BR
        }
        
[domain_realm]
        .kerberos.server = IFG.BR
        .ifg.br = IFG.BR
        ifg.br = IFG.BR
        ifg = IFG.BR
        IFG0 = IFG.BR

[appdefaults]
        pam = {
                ticket_lifetime = 1d
                renew_lifetime = 1d
                forwardable = true
                proxiable = false
                minimum_uid = 1
        }