[Global]
   
   workgroup = IFG0
   security = ads
   realm = IFG.BR

   vfs objects = acl_xattr
   map acl inherit = yes
   store dos attributes = yes

   # encrypt passwords = yes
   
   # client signing = auto
   
   # Allow offline/cached credentials and ticket refresh
   winbind offline logon = yes
   winbind refresh tickets = yes
   # winbind expand groups = 1

   # Do not require that login usernames include the default domain
   winbind use default domain = yes


   # Use a unified keytab to store obtained Kerberos tickets
   dedicated keytab file = /etc/krb5.keytab
   kerberos method = secrets and keytab

   # No Printers
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

   # UID/GID mapping for local users
   idmap config * : backend = tdb
   idmap config * : range = 3000-7999

   # UID/GID mapping for domain users
   idmap config IFG : backend = rid
   idmap config IFG : range = 10000-999999

   template shell = /bin/bash
   template homedir = /home/%U