#!/bin/bash

plymouth change-mode --updates
gSysUpdateMsg="Inicializando Sistema..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"

# Clock sync
gSysUpdateMsg="Sincronizando relógio..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
timedatectl set-ntp true
hwclock --systohc

# Goylin System Update
gSysUpdateMsg="Buscando updates..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
pacman -Sy

gSysUpdateMsg="Atualizando Configuração do Sistema..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
pacman -S --overwrite "*" --noconfirm --needed $(pacman -Qe | grep "^g-" | cut -d" " -f1)

gSysUpdateMsg="Atualizando Programas..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
pacman -S --overwrite "*" --noconfirm --needed $(pacman -Qe | grep "^gapp-" | cut -d" " -f1)

gSysUpdateMsg="Atualizando o Perfil..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
pacman -S --overwrite "*" --noconfirm --needed $(pacman -Qe | grep "^gp-" | cut -d" " -f1)

# PKGs Update
gSysUpdateMsg="Instalando Atualizações, aguarde..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
pacman -Su --noconfirm --needed

# PKGs Cache Clean Up
gSysUpdateMsg="Limpando Cache..."
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"
pacman -Scc --noconfirm

# Init System
gSysUpdateMsg="Bem Vindo!"
echo "${gSysUpdateMsg}"
plymouth display-message --text="${gSysUpdateMsg}"