#!/bin/bash

plymouth change-mode --system-upgrade

plymouth display-message --text="Procurando atualizações..."
[ -f /var/lib/pacman/db.lck ] && rm -vf /var/lib/pacman/db.lck
pacman -Sy

plymouth display-message --text="Atualizando perfil..."
pacman -S --overwrite "*" --noconfirm --ask=4 --needed g-patch
pacman -S --overwrite "*" --noconfirm --ask=4 --needed $(pacman -Qe | grep "^gp-" | cut -d" " -f1)

if [[ -f /etc/gUpdate || -f /etc/gUpgrade ]]; then
	plymouth display-message --text="Atualizando Configurações do Sistema..."
	pacman -S --overwrite "*" --noconfirm --ask=4 --needed $(pacman -Qe | grep "^g-" | cut -d" " -f1)

	plymouth display-message --text="Atualizando lista de programas..."
	pacman -S --overwrite "*" --noconfirm --ask=4 --needed $(pacman -Qe | grep "^gapp-" | cut -d" " -f1)

	[ -f /etc/gUpdate ] && rm -f /etc/gUpdate

	if [ -f /etc/gUpgrade ]; then
		plymouth display-message --text="Atualizando pacotes..."
		pacman -Su --noconfirm --needed && rm -f /etc/gUpgrade
	fi
fi

plymouth display-message --text="Removendo orfãos..."
pacman -Rsn $(pacman -Qtdq) --noconfirm

plymouth display-message --text="Limpando Cache..."
pacman -Scc --noconfirm

plymouth display-message --text="Limpando Logs..."
journalctl --vacuum-time=4weeks

plymouth display-message --text="Desligando..."

exit 0