#!/bin/bash

_removeHomeFile () {
	for userInHome in /home/*; do
		userHome=$(basename $userInHome)
		[ -f /home/"$userHome"/"$1" ] && rm -vf /home/"$userHome"/"$1"
	done
	[ -f /etc/skel/"$1" ] rm -vf /etc/skel/"$1"
}

_cleanHome () {
	for userInHome in /home/*; do
		userHome=$(basename $userInHome)
		rm -rvf /home/"$userHome"/.*
		rm -vf /home/"$userHome"/Desktop/*.desktop
	done
}

post_upgrade() {
	_cleanHome
}

# post_install() {
# }