#!/bin/bash

_hide_desktop() {
	file="/usr/share/applications/$1"
	[ -f "${file}" ] && sed -i '/^NoDisplay=/d; $aNoDisplay=true' "${file}"
	return 0
}

_hide_desktop_entry() {
	_hide_desktop "org.kde.kmenuedit.desktop"
	_hide_desktop "lstopo.desktop"
	_hide_desktop "assistant.desktop"
	_hide_desktop "qdbusviewer.desktop"
	_hide_desktop "linguist.desktop"
	_hide_desktop "designer.desktop"
	_hide_desktop "qvidcap.desktop"
	_hide_desktop "qv4l2.desktop"
	_hide_desktop "kde_wacom_tabletfinder.desktop"
}

##

post_install() {
	chattr +i /etc/xdg/kdeglobals
	_hide_desktop_entry
}

pre_upgrade() { chattr -i /etc/xdg/kdeglobals; }

post_upgrade() {
	chattr +i /etc/xdg/kdeglobals
	_hide_desktop_entry
}