#!/bin/bash

output_name=$(xrandr | grep ' connected' | awk '{ print $1 }')
highest_restolution=$(xrandr | grep "$output_name" -A 1 | grep -o '[0-9]\+x[0-9]\+' | sort -t 'x' -n -k2 | tail -n1)
[ "$DESKTOP_SESSION" == "i3" ] && xrandr --output "$output_name" --mode "$highest_restolution"
[[ "$DESKTOP_SESSION" == "plasma" || "$DESKTOP_SESSION" == "plasmax11" ]] && kscreen-doctor config output."$output_name".mode.0