#!/bin/bash

response_code=$(curl -s -o /dev/null -w "%{http_code}" "http://repo.goias.ifg.edu.br/goylin-web/index.html")

if [ "$response_code" == "200" ]; then
    /usr/bin/brave --app=http://repo.goias.ifg.edu.br/goylin-web/index.html --window-size=700,800
fi