#!/bin/bash

_lockGFiles() {
	chattr +i /etc/profile
	chattr +i /etc/xdg/user-dirs.defaults
	chattr +i /etc/X11/xorg.conf.d/00-keyboard.conf
}

_unlockGFiles() {
	chattr -i /etc/profile
	chattr -i /etc/xdg/user-dirs.defaults
	chattr -i /etc/X11/xorg.conf.d/00-keyboard.conf
}

post_install() {
	printf "\nsource /etc/profile.goylin\n" | tee -a /etc/profile 1> /dev/null
	
	_lockGFiles

	systemctl enable bluetooth
}

pre_upgrade() {
	_unlockGFiles
}

post_upgrade() {
	_lockGFiles
}