# font-name=Font to use
# xft-dpi=Resolution for Xft in dots per inch
# xft-rgba=Type of subpixel antialiasing (none/rgb/bgr/vrgb/vbgr)

[Greeter]
background=/usr/share/goylin/wallpapers/wall-24-1.jpg
clock-format=%l:%M %p
stretch-background-across-monitors=false
only-on-monitor=-1 # -1 means "follow the mouse"
show-power=false
activate-numlock=true
draw-grid=false
show-hostname=true
show-a11y=false
show-keyboard=false
show-clock=true
show-quit=true
draw-user-backgrounds=false
enable-hidpi=auto
hidden-users=admin
screen-reader=false
high-contrast=false
onscreen-keyboard=false
xft-antialias=true
# xft-hintstyle=hintfull
# theme-name=breeze-dark
# icon-theme-name=breeze-dark
# logo=/usr/share/goylin/icons/goylin.svg
# other-monitors-logo=/usr/share/goylin/icons/goylin.svg