#!/bin/sh

# Enable remote user login on Desktop Enviroment
eval $(dbus-launch --sh-syntax)

# User Home Update
cp -fru /etc/skel/. $HOME
xdg-user-dirs-update
[ -d "${HOME}/Área de trabalho" ] && rm -vr "${HOME}/Área de trabalho"

# Fix Config File User Names
# Goylin-Plasma
[ -f ${HOME}/.local/share/user-places.xbel ] && sed -i "s/_USERNAME_/$(whoami)/g" ${HOME}/.local/share/user-places.xbel
[ -f ${HOME}/.config/ktrashrc ] && sed -i "s/_USERNAME_/$(whoami)/g" ${HOME}/.config/ktrashrc
# Goylin-App-Audio
# [ -f ${HOME}/.config/ardour8/ui_config ] && sed -i "s/_USERNAME_/$(whoami)/g" ${HOME}/.config/ardour8/ui_config
# [ -f ${HOME}/.config/ardour8/config ] && sed -i "s/_USERNAME_/$(whoami)/g" ${HOME}/.config/ardour8/config
# [ -f ${HOME}/.lmmsrc.xml ] && sed -i "s/_USERNAME_/$(whoami)/g" ${HOME}/.lmmsrc.xml
# Goylin-App-Image
# [ -f ${HOME}/.config/kritarc ] && sed -i "s/_USERNAME_/$(whoami)/g" ${HOME}/.config/kritarc

# Remove Unused Guest files
[ "$(whoami)" == "guest" ] && [ -f ${HOME}/Desktop/public.desktop ] && rm -v ${HOME}/Desktop/public.desktop

# Ensure .desktop files execution
chmod +x ${HOME}/Desktop/*.desktop
chmod +x ${HOME}/.config/autostart/*.desktop