#!/bin/bash

_lockGFiles() {
	chattr +i /usr/lib/os-release
	chattr +i /etc/lightdm/lightdm.conf
}

_unlockGFiles() {
	chattr -i /usr/lib/os-release
	chattr -i /etc/lightdm/lightdm.conf
}

_setProfile() {
	sed -i "s/core/geotec/g" /usr/lib/os-release
	sed -i "s/user-session=plasma$/user-session=plasmax11/g" /etc/lightdm/lightdm.conf
}

post_install() {
	_unlockGFiles
	_setProfile
	_lockGFiles
}

post_upgrade() {
	_unlockGFiles
	_setProfile
	_lockGFiles
}