#!/bin/bash

_lockGFiles() {
	chattr +i /usr/lib/os-release
	chattr +i /etc/xdg/kdeglobals
}

_unlockGFiles() {
	chattr -i /usr/lib/os-release
	chattr -i /etc/xdg/kdeglobals
}

_setProfile() {
	sed -i "s/core/radio/g" /usr/lib/os-release
	sed -i "s/goylin.desktop/goylindark.desktop/g" /etc/xdg/kdeglobals
}

post_install() {
	_unlockGFiles
	_setProfile
	_lockGFiles
}

post_upgrade() {
	_unlockGFiles
	_setProfile
	_lockGFiles
}