[Config]

ShowState=1
; Initial Sivar window state
; Leave blank for default or one of the followings
; #define SW_HIDE        0
; #define SW_SHOWNORMAL  1
; #define SW_SHOWMINIMIZED    2
; #define SW_SHOWMAXIMIZED    3


[Registration]
ProgramFolder=C:\Documents and Settings\All Users\Start Menu\Programs\Sisvar\Sisvar
UserType=PR
