[options]
HoldPkg = pacman glibc
Architecture = auto
Color
ILoveCandy
CheckSpace
UseSyslog
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

# [core]
# Include = /etc/pacman.d/mirrorlist

# [extra]
# Include = /etc/pacman.d/mirrorlist

# [community]
# Include = /etc/pacman.d/mirrorlist

# [multilib]
# Include = /etc/pacman.d/mirrorlist

# # PROD

# [goylin-repo]
# SigLevel = Optional TrustAll
# Server = http://10.11.0.111/goylin-repo

# [goylin-repo-a]
# SigLevel = Optional TrustAll
# Server = http://10.11.0.111/goylin-repo-a

# [goylin-repo-g]
# SigLevel = Optional TrustAll
# Server = http://10.11.0.111/goylin-repo-g

# [goylin-repo-c]
# SigLevel = Optional TrustAll
# Server = http://10.11.0.111/goylin-repo-c

# # DEV

[goylin-repo]
SigLevel = Optional TrustAll
Server = http://10.11.100.29/goylin-repo

[goylin-repo-a]
SigLevel = Optional TrustAll
Server = http://10.11.100.29/goylin-repo-a

[goylin-repo-g]
SigLevel = Optional TrustAll
Server = http://10.11.100.29/goylin-repo-g

[goylin-repo-c]
SigLevel = Optional TrustAll
Server = http://10.11.100.29/goylin-repo-c

[goylin-repo-w]
SigLevel = Optional TrustAll
Server = http://10.11.100.29/goylin-repo-w